version: "3.7"

services:
  app:
    container_name: "hr-worker"
    image: hr-worker:v1
    build: .
    environment:
      - TZ=America/Fortaleza
    networks:
      - hr-net
      - interna
networks:
  hr-net:
    external: true
  interna:
